#include<iostream>
#include<string>

using namespace std;

int main()
{
    string Red_Bird=R"(WWXKXNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWNKOkk0XWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMWWNWWMMMMMMMMMMMMMM
WWWWWXOoodOXWWWWWWMWWWWWWWMWWWWMMMMMMMMMMMMMN0kxkOXWMMMMMMMMMMMM
MWWWWWWXklcld0NWWWWWWWMMMWWWWWMMMMMMMMMMMMMW0xxxxxkXMMMMMMMMMMMM
WWWMMWWWN0o::coOXWMMWWWWWWMMWWWMMMMMMMMMMMMWN00O00KWMMMMMMMMMMMM
MWWWWWWMMWKo::::oONWWWMMWWWWWWMMMMMMMMMMXOkkkxxkxxxkkkKWMMMMMMMM
WWWMMWWWWWW0l;;;;:dXWWWWWWMMWWWMMMMMMMMWOollddlccoxollxNMMMMMMMM
MWWWWWWMMWWNx:;;;;;o0WMMWWWWWWMMMMMMMMMMOoodKWKO0XWkoodXMMMMMMMM
WWWMMWWWWWMWOc;;;;;;lKWWWWMMWWWMMMMMMMMMklloXWK00XWkoodXMMMMMMMM
MWWWWWWMWWWW0c,,,,,,;dNWWWWWWWMMMMMMMMMMklloKWK00XWxoldNMMMMMMMM
WWWWWWWWWWWWO:,,,,,,,c0WWWWWWWWMMMMMMMMMOllo0WK00XNxlldNMMMMMMMM
WWWWWWWWWWWNx;,,,,,,,;kWWWWWWWWMMMMMMMMMXdloxKKKKKOoloOWMMMMMMMM
WWWWWWWWWWWOc,,',,,,';kWWWWWWWWMMMMMMMMMMXkxOOKNX0Okx0WMMMMMMMMM
WWWWWWWWWW0l,','',,,'c0WWWWWWWWMMMMMMMMMMMWNK0KKK0KXWMMMMMMMMMMM
WWWWWWWWNOc,'''''''',dNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWMWWKd;''''''''''c0WWWWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMWWWW0l,'''''''''';kWMMWWWWWWMMMWWWWMMMWWWWWMMMWWWWWMMMWWWWMMMW
WWWMWOc,'''''''''',dNWWWWWMMWWWWWWMMWWWWWWMMWWWWWMMWWWWWWMMWWWWW
MWWW0c'''''''''''':0WWMMWWWWWMMMMWWWWWMMMWWWWNWMWWWWWMMWWWWWWMMW
WWWXo,''''''''''''oXWWWWWWMMWWWWWWMMMWWWWWWXxd0WWMMMWWWWWMMWWWWW
MMW0c'''''''''''''oXWWMMWWWWWWWXKXWWWWMWNKxc,lXWWWWWWMMWWWWWWMMW
WWW0c''''''''''''':OWWWWWWWWN0ddkKWWWWXOo:,,:kNWWWMMWWWWWWWWWWWW
WMWXl'''''''''''''':kXWWWWXkl,,dXNNX0dc;,,';xNWWWWWWWWWWWNOdOWWW
WWWWO:'''''''''''''',cxKKkc'..,oOkdc;,'''',dXWWWWWWWWWNKkl;;xWWW
WWWWNOc'''''''''''''''',;,'',,;::;,'''''',oXWWWWWNX0kdc;,''c0WWW
WWWWWWXx:'''...'..'''..'',;::;,''........;oxxddol:;,,'''',l0WWWW
WWWMWWWWXkl;'....'....',;:;,'...................''''''',cxXWWWWW
WMWWWWWMMWNKko:,'...',,,'...............  .....'''',;cdOXWWWMMWW
WWWMMWWWWWMMWWX0kdlc;,................   ....',;:ldk0XWWWMMWWWWW
MMWWWWWMMWWWWWMMMWWNK0OxdooooooooooolllooddddxO0XNWWWMMWWWWWWMMW
WWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWWWMWWWWWWMMWWWWWMMWWWWWWMMMWWWW
MWWWWWWMMWWWWMMWMWWWWWWWWWWWWWMWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWW)";

cout<<Red_Bird<<endl;
return 0;
}